apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailspin-client
  namespace: toyspin
  labels:
    app: tailspin-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailspin-client
  template:
    metadata:
      labels:
        app: tailspin-client
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: client
          image: ghcr.io/OWNER/REPO/tailspin-client:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: API_SERVER_URL
              value: http://tailspin-server.toyspin.svc.cluster.local:5100
            - name: HOST
              value: 0.0.0.0
            - name: PORT
              value: "4321"
          ports:
            - containerPort: 4321
          readinessProbe:
            httpGet:
              path: /
              port: 4321
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 4321
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: tailspin-client
  namespace: toyspin
spec:
  selector:
    app: tailspin-client
  ports:
    - name: http
      port: 80
      targetPort: 4321
  type: LoadBalancer
