apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailspin-server
  namespace: toyspin
  labels:
    app: tailspin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailspin-server
  template:
    metadata:
      labels:
        app: tailspin-server
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: server
          image: ghcr.io/OWNER/REPO/tailspin-server:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: ENABLE_DEBUG_ENDPOINTS
              value: "true"
          ports:
            - containerPort: 5100
          readinessProbe:
            httpGet:
              path: /api/games
              port: 5100
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/games
              port: 5100
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: tailspin-server
  namespace: toyspin
spec:
  selector:
    app: tailspin-server
  ports:
    - protocol: TCP
      port: 5100
      targetPort: 5100
